/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:sample_weight modes were coerced from
  ...
    to  
  ['...']
WARNING:tensorflow:sample_weight modes were coerced from
  ...
    to  
  ['...']
Found 839 images belonging to 1 classes.
Found 839 images belonging to 1 classes.
Found 106 images belonging to 1 classes.
Found 106 images belonging to 1 classes.
Train for 104 steps, validate for 14 steps
Epoch 1/40
104/104 - 36s - loss: 0.5361 - my_mean_iou: 0.5411 - acc: 0.7527 - val_loss: 0.6166 - val_my_mean_iou: 0.3620 - val_acc: 0.6800
Epoch 2/40
Traceback (most recent call last):
  File "train.py", line 84, in <module>
    main()
  File "/home/ma-user/work/Segmentation/Util/decorator.py", line 33, in inner2
    f(*args,**kwargs)
  File "/home/ma-user/work/Segmentation/Util/decorator.py", line 20, in inner
    ret = f(*args,**kwargs)
  File "train.py", line 75, in main
    verbose=2,
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 397, in fit
    prefix='val_')
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 771, in on_epoch
    self.callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.6/site-packages/tensorflow_core/python/keras/callbacks.py", line 302, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.6/site-packages/tensorflow_core/python/keras/callbacks.py", line 992, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.6/site-packages/tensorflow_core/python/keras/callbacks.py", line 1027, in _save_model
    self.model.save_weights(filepath, overwrite=True)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 1123, in save_weights
    self._trackable_saver.save(filepath, session=session)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/util.py", line 1168, in save
    file_prefix=file_prefix_tensor, object_graph_tensor=object_graph_tensor)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/util.py", line 1116, in _save_cached_when_graph_building
    save_op = saver.save(file_prefix)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.6/site-packages/tensorflow_core/python/training/saving/functional_saver.py", line 230, in save
    sharded_saves.append(saver.save(shard_prefix))
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.6/site-packages/tensorflow_core/python/training/saving/functional_saver.py", line 72, in save
    return io_ops.save_v2(file_prefix, tensor_names, tensor_slices, tensors)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1708, in save_v2
    ctx=_ctx)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1730, in save_v2_eager_fallback
    ctx=ctx, name=name)
  File "/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_